name: Sync JIRA Issues

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  sync-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Sync JIRA Issues to GitHub
        run: |
          python scripts/sync_jira_issues.py
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
