name: Sync JIRA Issues

on:
  push:  # Trigger the workflow on push events
    branches:
      - main  # Specify the branch to monitor, e.g., 'main' notes added to test trigger
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 * * * *'  # Example schedule to run every hour

jobs:
  sync-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Sync JIRA Issues to GitHub
        run: |
          python scripts/sync_jira_issues.py
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
